### PR TITLE
Add boost query feature

### PR DESCRIPTION
**Pull request by the-xs**
Set ```<bool name="useBoostQuery">true</bool>``` for the segmenter to activate bq rewritten:

```?q={!seg+defType=edismax}John+Smith+Jr``` will be converted to q=John+Smith&bq=suffix:Jr

### CODE REVIEW

**Comment by nmtien** [comment]
Thank you very much for the contribution
1) If i understand correctly for query "John Smith Jr" will be converted to "John Smith&bq=suffix:Jr"
What if the query is "John Smith Jr sing", will be it converted to "John Smith &bq=suffix:Jr sing
I read your change it seem there is no verification that the suffix "Jr" must be at the end of query.

2) In QuerySegmenterComponent
If we convert q=John Smith&bq=suffix:Jr, Solr will think q is "John Smith&bq=suffix:Jr", 
I think we should change to add bq directly to solrparams
modifiableSolrParams.set(DisMaxParams.BQ, suffix:Jr);

**Comment by otisg** [comment]
> I read your change it seem there is no verification that the suffix "Jr" must be at the end of query.

If this is a requirement maybe @the-xs could add a unit test?

**Comment by the-xs** [comment]
@nmtien and @otisg, 

so which behavior is preferred for "John Smith Jr Sing"? I believe usually people won't type suffix in the middle. If that is a presumption, a check can be added so not to extract it if it is in the middle.

Or it is always extracted, and add the bq to the query to the end. In this way, a problem is if search for a name contains the word that is in the dictionary, it will be accidentally extracted.

**Comment by the-xs** [comment]
For the  q is "John Smith&bq=suffix:Jr", looks like solr is smart enough to treat bq as bq instead of q. The unit test case in ```QuerySegmenterComponentTest``` can see the results are correctly returned.

**Comment by the-xs** [comment]
Added the fix for extracting the segment terms instead of replacing the query.
Changed to use ```modifiableSolrParams.set(DisMaxParams.BQ, bq);```

The unit test cases also modified to move "JR" to the middle of the query.

**Comment by nmtien** [comment]
The change in QuerySegmenterComponent for boost query look goods, but the change in QuerySegmenterQParser seem not works,

Query is converted to John  Smith&bq=suffix:"Jr"
and then parse to Lucene query +((name:john) ((name:smith name:bq name:suffix)) (name:jr))
So Solr doesn't recognize the bq=suffix:"Jr" in user query when parsing.

I think for QuerySegmenterQParser, we should add bootQueries apparently like this 

// Parse main query
QParser parser = subQuery(qstr, null);
Query query = parser.parse();

// Parse suffixBoostQueries 
...
// Add boost query to main query
/* * * Boosting Query * * */
suffixBoostQueries = XXX;
for(Query f : suffixBoostQueries) {
      query.add(f, BooleanClause.Occur.SHOULD);
}

**Comment by the-xs** [comment]
So what would happen for the case of regular segmenter, for example: q={!seg+defType=edismax}pizza+solr+is+working, will the query becoming: pizza+project:solr+is+working?

**Comment by nmtien** [comment]
Yes, it will be converted to pizza+project:solr+is+working
Solr parser can parse field:value in user query, so it works fine.

**Comment by the-xs** [comment]
working on it.

**Pull request merged**
